version: "3.8"
services:
  db:
    image: postgres:15
    container_name: nextjs-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextauth
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

